### ISSUE TITLE
"remove" action should remove the home directory

### ISSUE THREAD

**Issue by lrliu** [sous-chefs/users#137]
Everything works great but remove action is not deleting the removed user account's home directory. Is this intentional?

**Comment by nkadel-skyhook** [comment]
That's standard for the "userdel" command on Linux systems.

**Comment by lrliu** [comment]
If I use the native Chef module:
user 'tom' do
   action  :remove
end
It works perfectly fine removing both the account and its home directory.
The reason I want to use cookbook 'users' is the native one doesn't have
builtin way to deploy authorized_keys.

**Comment by lrliu** [comment]
And not if you run userdel -r

**Comment by nkadel-skyhook** [comment]
Then perhaps it should be databag enabled option, disabled by default? It contributes to databag complexity to support all the resources of other tools in chef, but it can be very useful.

**Comment by tas50** [comment]
It is intentional and I think we should provide an opt-in property for nuking the directories.

**Comment by TheLinuxNinja** [comment]
I just reached this issue after doing a search. I can't get the users cookbook to remove an existing user at all, much less remove the leftover home directory. What is the status on this?

**Comment by mengesb** [comment]
So I've handled this through wrapping the users cookbook... which took a bit of effort because I also wanted to remove any users that are effectively managed in the data bag that may have been added at one point.

It resulted in performing the same similar searches in the provider without as many conditions. In the end I got it working, but it wasn't a small effort to get the logic right. In this case, we've decided to leave the old directories behind, and created a cleanup to do this for us after-the-fact

**Comment by zjohcap** [comment]
I just added `manage_home rm_user['manage_home'] ||= false` to manager.rb in resources then bumped my version to 5.1.1 from 5.1.0.  After that all you need to do is add `"manage_home": true` to the data bag for the user you want to remove.  You, of course, also need to be sure to have `"action": "remove"` in the databag object.  This works for me on chef client 12.21. 

This should hold us over until this issue gets merged into a release.

**Comment by frank-m** [comment]
This has been fixed in #444
